<?php
session_start();
include '../model/RawMaterial.php';
$db = new RawMaterial();

$action = $_GET['action'];
....
    ....
    header("location:index.php?message=add-success");
....
    ....
    header("location:index.php?message=edit-success");
....
    ....
    header("location:index.php?message=delete-success");
} else {
    header("location:index.php");
}
