<?php
session_start();
include '../model/Product.php';
$db = new Product();

$action = $_GET['action'];
....
    ....
    header("location:index.php?message=add-success");
....
    ....
    header("location:index.php?message=edit-success");
....
    ....
    header("location:index.php?message=delete-success");
} else {
    header("location:index.php");
}
